### ISSUE TITLE
MoI3D for Linux *solved*

### ISSUE THREAD

**Issue by ghost** [cryinkfly/cryinkfly#1]
Hi, Steve! Thanks for your work on CAD packages install scripts for Linux!

Can you also make *MoI3D* install script for Linux, please?

- Homepage: https://moi3d.com

### Trial Releases for Windows

- MoI3D `v1.0` - http://web.archive.org/web/20081220103405/http://moi3d.com/download.htm
  - EXE: http://web.archive.org/web/http://moi3d.com/1.0/trial/moi_v1_trial_setup.exe
- MoI3D `v1.1` (update) - http://web.archive.org/web/20091231155830/http://moi3d.com/download.htm
  - EXE: http://web.archive.org/web/http://moi3d.com/1.0/update/moi_v1_1_update.exe
- MoI3D `v2.0` - http://web.archive.org/web/20101218103141/http://moi3d.com/download.htm
  - EXE: http://web.archive.org/web/http://moi3d.com/2.0/trial/moi_v2_trial_setup.exe
- MoI3D `v3.0` (last release for 32-bit) - http://web.archive.org/web/20200114112443/http://moi3d.com/download.htm
  - EXE: http://web.archive.org/web/http://moi3d.com/3.0/trial/moi_v3_trial_setup.exe
- MoI3D `v4.0` (**latest release**, 64-bit only) - http://moi3d.com/download.htm
  - EXE: http://web.archive.org/web/http://moi3d.com/4.0/trial/moi_v4_trial_setup.exe

**Comment by cryinkfly** [comment]
@Symbian9 I'll take a look. :+1: 

![Bildschirmfoto_2021-10-09_13-28-50](https://user-images.githubusercontent.com/79079633/136656206-6ea51e1e-51b9-4ae5-b902-7de1a5dddd76.png)

**Comment by cryinkfly** [comment]
@Symbian9 Here is the link: https://github.com/cryinkfly/Moment-of-Inspiration-MoI3D-for-Linux

**Comment by ghost** [comment]
Thanks!
